import mongoose from "mongoose";

const OrderSchema = new mongoose.Schema(
  {
    /* =====================
       CORE REFERENCES
    ====================== */
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    product: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product",
      required: true,
    },

    orderNumber: {
      type: String,
      unique: true,
      index: true,
    },

    /* =====================
       INPUT SIGNALS (NO PRICE LOGIC)
    ====================== */
    quantity: {
      type: Number,
      required: true,
      min: 1,
    },

    selectedDynamicAttributes: [
      {
        // Support both formats: ObjectId (legacy) and String (client)
        attributeType: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "AttributeType",
        },

        // Client sends this field name
        attributeTypeId: String,

        attributeName: String,

        // Made optional - will be auto-generated by controller
        pricingKey: String,

        // Support both field names
        value: mongoose.Schema.Types.Mixed,
        attributeValue: mongoose.Schema.Types.Mixed,

        label: String,

        // Price impact fields
        priceAdd: Number,
        priceMultiplier: Number,
        description: String,
        image: String,

        uploadedImages: [
          {
            data: Buffer,
            contentType: String,
            filename: String,
          },
        ],
      },
    ],

    /* =====================
       🔒 PRICE SNAPSHOT (IMMUTABLE)
    ====================== */
    priceSnapshot: {
      type: {
        basePrice: { type: Number, required: true },
        unitPrice: { type: Number, required: true },  // Same as basePrice
        quantity: { type: Number, required: true },

        appliedModifiers: [
          {
            pricingKey: String,
            modifierType: {
              type: String,
              enum: ["PERCENT_INC", "PERCENT_DEC", "FLAT_INC", "FLAT_DEC", "FIXED"],
            },
            value: Number,
            source: {
              type: String,
              enum: ["GLOBAL", "ZONE", "SEGMENT", "PRODUCT", "ATTRIBUTE", "PROMO_CODE", "ZONE_BOOK", "SEGMENT_BOOK"],
            },
            modifierId: {
              type: mongoose.Schema.Types.ObjectId,
              ref: "PriceModifier",
            },
            beforeAmount: Number,
            afterAmount: Number,
            reason: String,
            appliesOn: {
              type: String,
              enum: ["UNIT", "SUBTOTAL"],
            },
          },
        ],

        subtotal: { type: Number, required: true },
        gstPercentage: { type: Number, default: 0 },
        gstAmount: { type: Number, default: 0 },
        totalPayable: { type: Number, required: true },

        currency: { type: String, default: "INR" },
        calculatedAt: { type: Date, default: Date.now },
      },
      required: true,
      immutable: true,  // 🚨 CRITICAL: Prevents price tampering
    },

    /* =====================
       ORDER STATUS FLOW
    ====================== */
    status: {
      type: String,
      enum: [
        "REQUESTED", "requested",
        "DESIGN", "design",
        "APPROVED", "approved",
        "PRODUCTION", "production",
        "processing", // Added for department workflow
        "QC", "qc",
        "PACKED", "packed",
        "DISPATCHED", "dispatched",
        "DELIVERED", "delivered",
        "completed", // Added for department workflow
        "CANCELLED", "cancelled",
        "REJECTED", "rejected",
      ],
      default: "REQUESTED",
      index: true,
    },

    currentDepartment: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Department",
      default: null,
    },

    currentDepartmentIndex: {
      type: Number,
      default: 0,
    },

    // Department approval tracking - used by production workflow
    departmentStatuses: [{
      department: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Department",
        required: true,
      },
      status: {
        type: String,
        enum: ['pending', 'in_progress', 'paused', 'completed', 'stopped'],
        default: 'pending',
      },
      whenAssigned: Date,
      startedAt: Date,
      completedAt: Date,
      pausedAt: Date,
      stoppedAt: Date,
      operator: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
      notes: String,
    }],

    // Production timeline for audit trail
    productionTimeline: [{
      department: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Department",
      },
      action: {
        type: String,
        enum: ['requested', 'started', 'paused', 'resumed', 'completed', 'stopped', 'rejected'],
      },
      timestamp: {
        type: Date,
        default: Date.now,
      },
      operator: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
      notes: String,
    }],

    /* =====================
       DELIVERY
    ====================== */
    address: { type: String, required: true },
    pincode: { type: String, required: true },
    mobileNumber: { type: String, required: true },

    // Shipping cost and courier selection
    shippingCost: { type: Number, default: 0 },
    selectedCourier: {
      courierId: Number,
      courierName: String,
      estimatedDays: Number,
      rate: Number
    },

    /* =====================
       PAYMENT
    ====================== */
    advancePaid: { type: Number, default: 0 },

    paymentStatus: {
      type: String,
      enum: [
        "PENDING",           // Awaiting payment
        "PARTIAL",           // Partial payment received
        "COMPLETED",         // Full payment received
        "FAILED",            // Payment failed
        "REFUNDED",          // Fully refunded
        "PARTIALLY_REFUNDED" // Partial refund issued
      ],
      default: "PENDING",
      index: true,
    },

    paymentGatewayInvoiceId: String,

    // Enhanced payment tracking
    payment_details: {
      // Reference to PaymentTransaction
      transaction_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "PaymentTransaction"
      },

      // Gateway used for this order
      gateway_used: {
        type: String,
        enum: ['RAZORPAY', 'STRIPE', 'PHONEPE', 'PAYU', 'CASHFREE']
      },

      // Payment method used
      payment_method: {
        type: String,
        enum: ['UPI', 'CARD', 'NETBANKING', 'WALLET', 'QR', 'BANK_TRANSFER', 'EMI', 'COD', 'CREDIT']
      },

      // Capture timestamp
      captured_at: Date,

      // Total paid amount
      amount_paid: {
        type: Number,
        default: 0
      },

      // Refund summary
      refund_summary: {
        total_refunded: { type: Number, default: 0 },
        refund_count: { type: Number, default: 0 },
        last_refund_at: Date
      },

      // For split payments
      split_details: {
        is_split: { type: Boolean, default: false },
        platform_amount: Number,  // Amount retained by platform
        vendor_amount: Number,    // Amount to vendor/partner
        vendor_id: mongoose.Schema.Types.ObjectId
      }
    },


    /* =====================
       LEGACY FIELDS (DO NOT DELETE)
    ====================== */
    paperGSM: String,
    laminationType: String,
    specialEffects: [String],

    /* =====================
       AUDIT
    ====================== */
    notes: String,
    adminNotes: String,

    /* =====================
       NEW FIELDS - Production & Logistics
    ====================== */
    productionJobId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ProductionJob",
      index: true,
    },

    docketId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Docket",
      index: true,
    },

    logisticsProvider: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "LogisticsProvider",
    },

    trackingId: String,

    /* =====================
       DELIVERY TRACKING
    ====================== */
    estimatedDeliveryDate: Date,
    actualDeliveryDate: Date,

    // Production timeline tracking
    productionStartDate: Date,
    productionEndDate: Date,
    productionCompletedAt: Date,

    // Shipment scheduling
    shipmentScheduledDate: Date,
    shipmentCreatedViaProduction: {
      type: Boolean,
      default: false
    },

    deliveryStatus: {
      type: String,
      enum: ["PENDING", "DISPATCHED", "IN_TRANSIT", "OUT_FOR_DELIVERY", "DELIVERED", "FAILED"],
      default: "PENDING",
      index: true,
    },

    deliveryOTP: String,

    /* =====================
       ORDER HIERARCHY (for bulk orders)
    ====================== */
    isPriority: {
      type: Boolean,
      default: false,
    },

    parentOrderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
      // For bulk orders (30-in-1)
    },

    childOrders: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Order",
        // For split bulk orders
      },
    ],

    /* =====================
       DESIGNER SERVICE
    ====================== */
    designerSessionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "DesignerSession",
    },

    /* =====================
       PAYMENT & ERP
    ====================== */
    paymentGatewayId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PaymentGateway",
    },

    zohoInvoiceId: String,

    /* =====================
       DELIVERY RATING
    ====================== */
    deliveryRating: {
      agentRating: { type: Number, min: 1, max: 5 },
      customerRating: { type: Number, min: 1, max: 5 },
      feedback: String,
      ratedAt: Date,
    },

    /* =====================
       COURIER TRACKING (SHIPROCKET)
    ====================== */
    shiprocketOrderId: String,           // Shiprocket order ID
    shiprocketShipmentId: String,        // Shiprocket shipment ID
    awbCode: String,                      // Air Way Bill code for tracking
    courierPartner: String,               // Courier company name (e.g., "Delhivery")
    courierCompanyId: Number,             // Courier company ID from Shiprocket
    courierStatus: {
      type: String,
      enum: ['PENDING', 'PICKUP_SCHEDULED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'RTO', 'CANCELLED'],
      default: 'PENDING'
    },
    courierTrackingUrl: String,           // Shiprocket tracking URL
    courierTimeline: [{                   // Timeline of tracking events
      status: String,
      location: String,
      timestamp: Date,
      notes: String
    }],
    courierCharges: {                     // Courier pricing details
      freightCharge: { type: Number, default: 0 },
      codCharges: { type: Number, default: 0 },
      totalCharge: { type: Number, default: 0 }
    },
    pickupDetails: {                      // Pickup information
      pickupLocationId: String,
      pickupLocationName: String,
      pickupAddress: String,
      pickupPincode: String,
      scheduledPickupTime: Date,
      actualPickupTime: Date
    },
    dispatchedAt: Date,                   // When order was dispatched
    deliveredAt: Date,                    // When delivered
  },
  { timestamps: true }
);

/* =====================
   INDEXES
====================== */
OrderSchema.index({ user: 1, createdAt: -1 });
OrderSchema.index({ status: 1 });
// New indexes for delivery and production tracking
OrderSchema.index({ deliveryStatus: 1, estimatedDeliveryDate: 1 });
OrderSchema.index({ productionJobId: 1, status: 1 });
OrderSchema.index({ docketId: 1 });
OrderSchema.index({ parentOrderId: 1 });

/* =====================
   ORDER NUMBER
====================== */
OrderSchema.pre("save", function (next) {
  if (!this.orderNumber) {
    const ts = Date.now();
    const rand = Math.floor(Math.random() * 10000);
    this.orderNumber = `ORD-${ts}-${rand.toString().padStart(4, "0")}`;
  }
  next();
});

/* =====================
   BACKWARD COMPATIBILITY
====================== */
// Virtual field for legacy code that references totalPrice
OrderSchema.virtual('totalPrice').get(function () {
  return this.priceSnapshot?.totalPayable || 0;
});

// Ensure virtuals are included in JSON and Object representations
OrderSchema.set('toJSON', { virtuals: true });
OrderSchema.set('toObject', { virtuals: true });

export default mongoose.model("Order", OrderSchema);
